server:
  port: 8084

spring:
  application:
    name: sheep-merchant
  cloud:
    nacos:
      server-addr: 192.168.168.100:8848
      username: nacos
      password: nacos
      discovery:
        group: SHEEP_MALL
      config:
        group: SHEEP_MALL
        file-extension: yaml
        import-check:
          enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sheep_merchant_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:123456}
      database: 1
      timeout: 3s
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4
          max-wait: 3s

mybatis-plus:
  type-aliases-package: com.xs.sheepaimall.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
